project:
  type: book
  resources:
  - webr-serviceworker.js
  - webr-worker.js
  - coi-serviceworker.js
book:
  title: HuGen2071 book
  author: Daniel E. Weeks
  date: today
  date-format: long
  chapters:
  - index.qmd
  - preparation.qmd 
  - intro.qmd
  - logistics.qmd
  - Readings.qmd
  - gitIntro.qmd
  - Git_commands.Qmd
  - RBasicsLecture.qmd
  - Rbasics.qmd
  - RFactors.qmd
  - R_char_exer.Qmd
  - RLoops.qmd
  - loops.qmd
  - conditionals.qmd
  - loops_part2.qmd
  - functions.qmd
  - R_Functions.Qmd
  - tidyverse.qmd
  - exercise_tidyverse.Qmd
  - recoding_reshaping_interactive.Qmd
  - merging_exercise.Qmd
  - R_graphics_exercises.Qmd
  - reorder_exercise.Qmd
  - EDA.Qmd
  - R_questions.qmd
  - Basic_Unix_commands.Qmd
  - summary.qmd
  - references.qmd
  appendices:
  - TechnicalDetails.qmd
  - webR_test.qmd
  - JSLinux.qmd
  - webLinux.qmd
bibliography: references.bib
format:
  html:
    theme: cosmo
    css: include/webex.css
    include-after-body: include/webex.js
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/danieleweeks\.github\.io\/HuGen2071'
  pdf:
    documentclass: scrreprt
editor: visual
filters: 
  - webr
