project:
  type: book

book:
  title: "HuGen2071 book"
  author: "Daniel E. Weeks"
  date: October 2, 2022
  chapters:
    - index.qmd
    - preparation.qmd
    - intro.qmd
    - logistics.qmd 
    - Rbasics.qmd
    - R_char_exer.Qmd
    - R_Functions.Qmd
    - exercise_tidyverse.Qmd
    - recoding_reshaping_interactive.Qmd
    - merging_exercise.Qmd
    - R_graphics_exercises.Qmd
    - reorder_exercise.Qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

