project:
  type: book

book:
  title: "HuGen2071 book"
  author: "Daniel E. Weeks"
  date: August 9, 2022
  chapters:
    - index.qmd
    - preparation.qmd
    - intro.qmd
    - logistics.qmd 
    - Rbasics.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

