---
editor: 
  mode: source
---

# Linux terminal

## Interactive Linux terminal

Here is an interactive Linux terminal (x86 Alpine Linux 3.12.0) created by the [copy.sh](http://copy.sh/v86/) project.

You can upload files to it by clicking the arrow below the terminal window.

This virtual Unix machine has a throttled very slow connection to the internet, so to install files and programs, it is better to download them to your computer outside of the browser, and then use the upload button to upload them onto this virtual machine.  

For example, the 32-bit version of PLINK2 can be installed in this manner: 

1. Download the Linux 32-bit PLINK2 zip file from <https://www.cog-genomics.org/plink/2.0/>
2. Unzip the downloaded file.
3. Use the upload arrow here below the terminal window to upload the `plink2` binary.
4. Make the `plink2` binary executable via this Unix command: `chmod +x plink2`
5. Run PLINK2 via this Unix command: `./plink2`

```{=html}
<iframe width="100%" height="800" src="https://bellard.org/jslinux/vm.html?url=alpine-x86.cfg&mem=192" allowfullscreen scrolling="yes" class="iframe-class" frameborder="0"></iframe>
```
