# Unix Scripting

## Unix Scripting

Here's a recording of this lecture (59 minutes 17 seconds):

[Recording](https://pitt.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=93838d98-bbeb-4023-a63b-b38e0101319f){.external target="_blank"}

<iframe credentialless src="https://pitt.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=93838d98-bbeb-4023-a63b-b38e0101319f&amp;autoplay=false&amp;offerviewer=true&amp;showtitle=true&amp;showbrand=true&amp;captions=true&amp;interactivity=all" height="405" width="720" style="border: 1px solid #464646;" allowfullscreen allow="autoplay">

</iframe>

## Unix Scripting slides

[PDF slide set](pdfs/unix_miscellaneous.pdf){target="_blank"}

<iframe width="100%" height="800" src="pdfs/unix_scripting.pdf">

</iframe>

## Questions

### Question 1

Which of the following are true about Unix variables?

```{r, echo=FALSE}
library(webexercises)
choices = c(
"Use $ both to set and access the value of a variable",
answer="Use $ to access but not to set the value of a variable",
"Only put $ in front of a variable when initializing a for loop",
"Using $ in front of a variable is always optional"
)
```

`r longmcq(choices)`

### Question 2

What will this do?
```
for file in `ls *.txt`
do
  rm $file
  echo file deleted
done
```

```{r, echo=FALSE}
library(webexercises)
choices = c(
"Just list all of the files in your working directory",
answer="Delete all .txt files in your working directory",
answer="The same thing it would do if you used for file in $(ls *.txt)",
"Print out a helpful message saying the names of the deleted files"
)
```

`r longmcq(choices)`

### Question 3

Which of the following are true of `find -exec` and `find | xargs`?

```{r, echo=FALSE}
library(webexercises)
choices = c(
answer="They both can be used to flexibly search for files and run commands on them.",
answer="By default they can only run relatively simple commands.",
answer="By using a child shell, they can run more complicated commands"
)
```

`r longmcq(choices)`